-- SocialSip: esquema independiente para Supabase/PostgreSQL
-- Ejecutar desde Supabase Dashboard > SQL Editor > New query.
-- No contiene datos de prueba ni operaciones destructivas.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  city text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz not null default now(),
  constraint friendships_no_self check (user_id <> friend_id),
  constraint friendships_unique_pair unique (user_id, friend_id)
);

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  venue_id bigint not null references public.venues(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'ended')),
  note text,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_url text not null,
  media_type text not null default 'image' check (media_type in ('image', 'video')),
  audio_url text,
  audio_name text,
  caption text check (char_length(caption) <= 500),
  visibility text not null default 'friends' check (visibility in ('friends', 'public')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create index if not exists friendships_user_idx on public.friendships(user_id, status);
create index if not exists friendships_friend_idx on public.friendships(friend_id, status);
create index if not exists checkins_user_status_idx on public.checkins(user_id, status, created_at desc);
create index if not exists stories_user_expiry_idx on public.stories(user_id, expires_at desc);
create index if not exists stories_visibility_expiry_idx on public.stories(visibility, expires_at desc);

alter table public.profiles enable row level security;
alter table public.venues enable row level security;
alter table public.friendships enable row level security;
alter table public.checkins enable row level security;
alter table public.stories enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.email
  )
  on conflict (id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Profiles: el usuario puede leer y editar su propio perfil.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Venues: lectura pública para usuarios autenticados; creación autenticada.
drop policy if exists venues_select_authenticated on public.venues;
create policy venues_select_authenticated on public.venues for select to authenticated using (true);
drop policy if exists venues_insert_authenticated on public.venues;
create policy venues_insert_authenticated on public.venues for insert to authenticated with check (true);

-- Amistades: cada usuario administra sus solicitudes y puede ver amistades relacionadas.
drop policy if exists friendships_select_related on public.friendships;
create policy friendships_select_related on public.friendships for select to authenticated
using (user_id = auth.uid() or friend_id = auth.uid());
drop policy if exists friendships_insert_as_user on public.friendships;
create policy friendships_insert_as_user on public.friendships for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists friendships_update_related on public.friendships;
create policy friendships_update_related on public.friendships for update to authenticated
using (user_id = auth.uid() or friend_id = auth.uid())
with check (user_id = auth.uid() or friend_id = auth.uid());

-- Check-ins: propios y de amistades aceptadas.
drop policy if exists checkins_select_visible on public.checkins;
create policy checkins_select_visible on public.checkins for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.user_id = auth.uid() and f.friend_id = checkins.user_id)
        or (f.friend_id = auth.uid() and f.user_id = checkins.user_id))
  )
);
drop policy if exists checkins_insert_own on public.checkins;
create policy checkins_insert_own on public.checkins for insert to authenticated with check (user_id = auth.uid());
drop policy if exists checkins_update_own on public.checkins;
create policy checkins_update_own on public.checkins for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Historias: públicas, propias o de amistades aceptadas; solo el dueño puede insertar/eliminar.
drop policy if exists stories_select_visible on public.stories;
create policy stories_select_visible on public.stories for select to authenticated
using (
  user_id = auth.uid()
  or visibility = 'public'
  or (
    visibility = 'friends'
    and exists (
      select 1 from public.friendships f
      where f.status = 'accepted'
        and ((f.user_id = auth.uid() and f.friend_id = stories.user_id)
          or (f.friend_id = auth.uid() and f.user_id = stories.user_id))
    )
  )
);
drop policy if exists stories_insert_own on public.stories;
create policy stories_insert_own on public.stories for insert to authenticated with check (user_id = auth.uid());
drop policy if exists stories_delete_own on public.stories;
create policy stories_delete_own on public.stories for delete to authenticated using (user_id = auth.uid());

-- Storage inicial para Historias. Es público para simplificar la primera prueba.
-- Más adelante puede cambiarse a privado y usar URLs firmadas.
insert into storage.buckets (id, name, public)
values ('stories', 'stories', true)
on conflict (id) do update set public = true;

drop policy if exists stories_storage_insert_own on storage.objects;
create policy stories_storage_insert_own on storage.objects for insert to authenticated
with check (bucket_id = 'stories' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists stories_storage_update_own on storage.objects;
create policy stories_storage_update_own on storage.objects for update to authenticated
using (bucket_id = 'stories' and owner_id = auth.uid()::text);
drop policy if exists stories_storage_delete_own on storage.objects;
create policy stories_storage_delete_own on storage.objects for delete to authenticated
using (bucket_id = 'stories' and owner_id = auth.uid()::text);
