-- Sky Night: cola segura para limpiar archivos de historias eliminadas o expiradas

create table if not exists public.story_storage_cleanup (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_url text,
  audio_url text,
  created_at timestamptz not null default now(),
  cleaned_at timestamptz
);

create index if not exists story_storage_cleanup_pending_idx
  on public.story_storage_cleanup (user_id, created_at)
  where cleaned_at is null;

alter table public.story_storage_cleanup enable row level security;

drop policy if exists story_storage_cleanup_select_own on public.story_storage_cleanup;
create policy story_storage_cleanup_select_own on public.story_storage_cleanup
for select to authenticated
using (user_id = auth.uid());

drop policy if exists story_storage_cleanup_update_own on public.story_storage_cleanup;
create policy story_storage_cleanup_update_own on public.story_storage_cleanup
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, update on table public.story_storage_cleanup to authenticated;

create or replace function public.queue_story_storage_cleanup()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.story_storage_cleanup (user_id, media_url, audio_url)
  values (old.user_id, old.media_url, old.audio_url);
  return old;
end;
$$;

drop trigger if exists story_storage_cleanup_after_delete on public.stories;
create trigger story_storage_cleanup_after_delete
after delete on public.stories
for each row execute function public.queue_story_storage_cleanup();

revoke all on function public.queue_story_storage_cleanup() from public;
